name: farmtohome_landing
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  youtube_player_flutter:
  url_launcher:
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  flutter_lints:

flutter_launcher_icons:
  image_path_android: "assets/icon/play_store_512.png"
  image_path_ios: "assets/icon/1024.png"
  android: true 
  ios: true 
  adaptive_icon_background: "assets/images/background.png" 
  adaptive_icon_foreground: "assets/icon/play_store_512.png" 
  adaptive_icon_foreground_inset: 16 
  adaptive_icon_monochrome: "assets/icon/play_store_512.png" 
  min_sdk_android: 21 
  remove_alpha_ios: true
  background_color: "#212121"
  web:
    generate: true
    image_path: "assets/icon/play_store_512.png"
    background_color: "#212121"
    theme_color: "#212121"
  windows:
    generate: true
    image_path: "assets/icon/play_store_512.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/icon/play_store_512.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/svg/
    - assets/sounds/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf

    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Thin.otf
        - asset: assets/fonts/Metropolis-ThinItalic.otf
          style: italic
        - asset: assets/fonts/Metropolis-Light.otf
        - asset: assets/fonts/Metropolis-LightItalic.otf
          style: italic
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-RegularItalic.otf
          style: italic
        - asset: assets/fonts/Metropolis-Medium.otf
        - asset: assets/fonts/Metropolis-MediumItalic.otf
          style: italic
        - asset: assets/fonts/Metropolis-SemiBold.otf
        - asset: assets/fonts/Metropolis-SemiBoldItalic.otf
          style: italic
        - asset: assets/fonts/Metropolis-Bold.otf
        - asset: assets/fonts/Metropolis-BoldItalic.otf
          style: italic
        - asset: assets/fonts/Metropolis-ExtraBold.otf
        - asset: assets/fonts/Metropolis-ExtraBoldItalic.otf
          style: italic
        - asset: assets/fonts/Metropolis-Black.otf
        - asset: assets/fonts/Metropolis-BlackItalic.otf
          style: italic

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf