name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - master   # or "main" if your repo uses main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # replace with your Flutter version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build Flutter web app
      - name: Build web
        run: flutter build web --release

      # Add CNAME file for custom domain
      - name: Add CNAME
        run: echo "farmtohome.live" > build/web/CNAME

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
